/*
 * ARM NVIDIA Tegra2 emulation.
 *
 * Copyright (c) 2014-2015 Dmitry Osipenko <digetx@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 *  for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, see <http://www.gnu.org/licenses/>.
 */

/* Autogenerated from TRM v02p */

#ifndef TEGRA_ARBGNT_ICTLR_H
#define TEGRA_ARBGNT_ICTLR_H

#define TYPE_TEGRA_ARBGNT_ICTLR "tegra.arb_gnt_ictlr"
#define TEGRA_ARBGNT_ICTLR(obj) OBJECT_CHECK(tegra_arb_gnt_ictlr, (obj), TYPE_TEGRA_ARBGNT_ICTLR)

#define CPU_STATUS_OFFSET 0x0
#define CPU_STATUS_RESET  0x00000000

#define CPU_ENABLE_OFFSET 0x4
#define CPU_ENABLE_RESET  0x00000000

#define COP_STATUS_OFFSET 0x8
#define COP_STATUS_RESET  0x00000000

#define COP_ENABLE_OFFSET 0xC
#define COP_ENABLE_RESET  0x00000000

typedef struct tegra_arb_gnt_ictlr_state {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    uint32_t pri_ictlr_arbgnt_cpu_enable;
    uint32_t pri_ictlr_arbgnt_cop_status;
    uint32_t pri_ictlr_arbgnt_cop_enable;
} tegra_arb_gnt_ictlr;

#endif // TEGRA_ARBGNT_ICTLR_H
