/*
 * ARM NVIDIA Tegra2 emulation.
 *
 * Copyright (c) 2014-2015 Dmitry Osipenko <digetx@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 *  for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, see <http://www.gnu.org/licenses/>.
 */

/* Autogenerated from TRM v02p */

#ifndef TEGRA_TIMER_H
#define TEGRA_TIMER_H

#define PTV_OFFSET 0x0
#define PTV_RESET  0x00000000
typedef union ptv_u {
    struct {
        unsigned int tmr_ptv:29;            /* Trigger Value: count trigger value (count length). This is in n+1 scheme. If you program the value n, the count trigger value will actually be n+1 */
        unsigned int undefined_bit_29:1;
        unsigned int per:1;                 /* Enable Periodic Interrupt; 0 = DISABLE; 1 = ENABLE */
        unsigned int en:1;                  /* Enable Timer; 0 = DISABLE; 1 = ENABLE */
    };

    uint32_t reg32;
} ptv_t;

#define PCR_OFFSET 0x4
#define PCR_RESET  0x00000000
#define PCR_WRMASK 0xE0000000
typedef union pcr_u {
    struct {
        unsigned int tmr_pcv:29;            /* Counter value: decrements from PTV */
        unsigned int undefined_bit_29:1;
        unsigned int intr_clr:1;            /* 1 = clears the interrupt, 0 = no affect. Write-1-to-Clear */
        unsigned int undefined_bit_31:1;
    };

    uint32_t reg32;
} pcr_t;

#define DEFINE_REG32(reg) reg##_t reg

typedef struct tegra_timer_state {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    ptimer_state *ptimer;
    DEFINE_REG32(ptv);
    DEFINE_REG32(pcr);
    qemu_irq irq;
    int irq_sts;
} tegra_timer;

#endif // TEGRA_TIMER_H
