/*
 * ARM NVIDIA Tegra2 emulation.
 *
 * Copyright (c) 2014-2015 Dmitry Osipenko <digetx@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 *  for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, see <http://www.gnu.org/licenses/>.
 */

/* Autogenerated from TRM v02p */

#ifndef TEGRA_HOST1X_SYNCPTS_H
#define TEGRA_HOST1X_SYNCPTS_H

#include "qemu/osdep.h"
#include "qemu/queue.h"
#include "qemu/thread.h"
#include "hw/irq.h"

#include "host1x_priv.h"

struct host1x_syncpt_waiter {
    unsigned int threshold:NV_HOST1X_SYNCPT_THESH_WIDTH;
    QLIST_ENTRY(host1x_syncpt_waiter) next;
    QemuEvent syncpt_ev;
    uint8_t base_id;
};

void host1x_unlock_syncpt_waiter(struct host1x_syncpt_waiter *waiter);
void host1x_unlock_syncpt_waiter_forced(struct host1x_syncpt_waiter *waiter);
void host1x_incr_syncpt(uint32_t syncpt_id);
void host1x_set_syncpt_count(uint32_t syncpt_id, uint32_t val);
uint32_t host1x_get_syncpt_count(uint32_t syncpt_id);
void host1x_set_syncpt_threshold(uint32_t syncpt_id, uint32_t val);
uint32_t host1x_get_syncpt_threshold(uint32_t syncpt_id);
void host1x_set_syncpt_base(uint32_t syncpt_base_id, uint32_t val);
void host1x_incr_syncpt_base(uint32_t syncpt_base_id, uint32_t val);
uint32_t host1x_get_syncpt_base(uint32_t syncpt_base_id);
void host1x_init_syncpt_waiter(struct host1x_syncpt_waiter *waiter);
void host1x_wait_syncpt(struct host1x_syncpt_waiter *waiter,
                        uint32_t syncpt_id, uint32_t threshold);
void host1x_wait_syncpt_base(struct host1x_syncpt_waiter *waiter,
                             uint32_t syncpt_id, uint32_t syncpt_base_id,
                             uint32_t offset);
void host1x_wait_syncpt_incr(struct host1x_syncpt_waiter *waiter,
                             uint32_t syncpt_id);
void host1x_init_syncpts(void);
void host1x_reset_syncpts(void);
int host1x_syncpt_threshold_is_crossed(uint32_t syncpt_id);

uint32_t host1x_get_syncpts_irq_status(void);
uint32_t host1x_get_syncpts_cpu_irq_status(void);
uint32_t host1x_get_syncpts_cop_irq_status(void);
uint32_t host1x_get_syncpts_dst_mask_low(void);
uint32_t host1x_get_syncpts_dst_mask_high(void);
void host1x_enable_syncpts_irq_mask(enum hcpu cpu_id, uint32_t enable_mask);
void host1x_set_syncpts_irq_dst_mask(int part, uint32_t mask);
void host1x_clear_syncpts_irq_dst_mask(uint32_t clear_mask);
void host1x_set_syncpt_irq(uint8_t syncpt_id);
void host1x_clear_syncpts_irq_status(enum hcpu cpu_id, uint32_t clear_mask);
void host1x_init_syncpts_irq(qemu_irq *cpu_irq, qemu_irq *cop_irq);
void host1x_reset_syncpt_irqs(void);

#define INTSTATUS_OFFSET 0x0
#define INTSTATUS_RESET  0x00000000
typedef union intstatus_u {
    struct {
        unsigned int host_int:1;            /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int mpe_int:1;             /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int vi_int:1;              /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int epp_int:1;             /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int isp_int:1;             /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int gr2d_int:1;            /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int gr3d_int:1;            /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int undefined_bit_7:1;
        unsigned int display_int:1;         /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int displayb_int:1;        /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int hdmi_int:1;            /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int tvo_int:1;             /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int dsi_int:1;             /* 0 = NOT_PENDING 1 = PENDING */
        unsigned int undefined_bits_13_29:17;
        unsigned int syncpt_cpu0_int:1;     /* set if SYNC_SYNCPT_THRESH_CPU0_INT_STATUS has a pending interrupt 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_cpu1_int:1;     /* set if SYNC_SYNCPT_THRESH_CPU1_INT_STATUS has a pending interrupt 0 = NOT_PENDING 1 = PENDING */
    };

    uint32_t reg32;
} intstatus_t;

#define INTMASK_OFFSET 0x4
#define INTMASK_RESET  0x00000000
typedef union intmask_u {
    struct {
        unsigned int cpu0_int_mask_all:1;   /* 0 = DISABLE 1 = ENABLE */
        unsigned int cpu1_int_mask_all:1;   /* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_2_31:30;
    };

    uint32_t reg32;
} intmask_t;

#define INTC0MASK_OFFSET 0x8
#define INTC0MASK_RESET  0x00000000
typedef union intc0mask_u {
    struct {
        unsigned int host_int_c0mask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int mpe_int_c0mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int vi_int_c0mask:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int epp_int_c0mask:1;      /* 0 = DISABLE; 1 = ENABLE */
        unsigned int isp_int_c0mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int gr2d_int_c0mask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int gr3d_int_c0mask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bit_7:1;
        unsigned int display_int_c0mask:1;  /* 0 = DISABLE 1 = ENABLE */
        unsigned int displayb_int_c0mask:1; /* 0 = DISABLE 1 = ENABLE */
        unsigned int hdmi_int_c0mask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int tvo_int_c0mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int dsi_int_c0mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_13_31:19;
    };

    uint32_t reg32;
} intc0mask_t;

#define INTC1MASK_OFFSET 0xC
#define INTC1MASK_RESET  0x00000000
typedef union intc1mask_u {
    struct {
        unsigned int host_int_c1mask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int mpe_int_c1mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int vi_int_c1mask:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int epp_int_c1mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int isp_int_c1mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int gr2d_int_c1mask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int gr3d_int_c1mask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bit_7:1;
        unsigned int display_int_c1mask:1;  /* 0 = DISABLE 1 = ENABLE */
        unsigned int displayb_int_c1mask:1; /* 0 = DISABLE 1 = ENABLE */
        unsigned int hdmi_int_c1mask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int tvo_int_c1mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int dsi_int_c1mask:1;      /* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_13_31:19;
    };

    uint32_t reg32;
} intc1mask_t;

#define HINTSTATUS_OFFSET 0x20
#define HINTSTATUS_RESET  0x00000000
#define HINTSTATUS_WRMASK 0x7FFFFFFF
typedef union hintstatus_u {
    struct {
        unsigned int wait_int0:1;           /* WAIT has completed on channel 0 0 = NOT_PENDING 1 = PENDING */
        unsigned int wait_int1:1;           /* WAIT has completed on channel 1 0 = NOT_PENDING; 1 = PENDING */
        unsigned int wait_int2:1;           /* WAIT has completed on channel 2 0 = NOT_PENDING 1 = PENDING */
        unsigned int wait_int3:1;           /* WAIT has completed on channel 3 0 = NOT_PENDING 1 = PENDING */
        unsigned int wait_int4:1;           /* WAIT has completed on channel 4 0 = NOT_PENDING 1 = PENDING */
        unsigned int wait_int5:1;           /* WAIT has completed on channel 5 0 = NOT_PENDING 1 = PENDING */
        unsigned int wait_int6:1;           /* WAIT has completed on channel 6 0 = NOT_PENDING 1 = PENDING */
        unsigned int wait_int7:1;           /* WAIT has completed on channel 7 0 = NOT_PENDING 1 = PENDING */
        unsigned int undefined_bits_8_15:8;
        unsigned int rdma_inval_clreq_int:1;/* Invalid client request to read DMA 0 = NOT_PENDING 1 = PENDING */
        unsigned int rdma_buf_oflow_int0:1; /* Buffer overflow in read DMA port0 0 = NOT_PENDING 1 = PENDING */
        unsigned int rdma_buf_thold_int0:1; /* Buffer threshold reached in read DMA port0 0 = NOT_PENDING 1 = PENDING */
        unsigned int rdma_databuf_thold_int0:1;/* Read DMA data FIFO in port0 reached high level watermark 0 = NOT_PENDING 1 = PENDING */
        unsigned int undefined_bits_20_28:9;
        unsigned int csw_host1xw2mc_int:1;  /* Host write client FIFO has filled up */
        unsigned int timer_intp:1;          /* Timer Interrupt from the Protected Channel 0 = NOT_PENDING 1 = PENDING */
        unsigned int hintstatus_ext_int:1;  /* Additional interrupts pending in the HINSTATUS_EXT register 0 = NOT_PENDING 1 = PENDING */
    };

    uint32_t reg32;
} hintstatus_t;

#define HINTMASK_OFFSET 0x24
#define HINTMASK_RESET  0x00000000
typedef union hintmask_u {
    struct {
        unsigned int wait_intmask0:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int wait_intmask1:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int wait_intmask2:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int wait_intmask3:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int wait_intmask4:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int wait_intmask5:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int wait_intmask6:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int wait_intmask7:1;       /* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_8_15:8;
        unsigned int rdma_inval_clreq_intmask:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int rdma_buf_oflow_intmask0:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int rdma_buf_thold_intmask0:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int rdma_databuf_thold_intmask0:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_20_28:9;
        unsigned int csw_host1xw2mc_intmask:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int timer_intmaskp:1;      /* Timer Interrupt Mask for the Protected Channel 0 = DISABLE 1 = ENABLE */
        unsigned int hintstatus_ext_intmask:1;/* 0 = DISABLE 1 = ENABLE */
    };

    uint32_t reg32;
} hintmask_t;

#define HINTSTATUS_EXT_OFFSET 0x28
#define HINTSTATUS_EXT_RESET  0x00000000
typedef union hintstatus_ext_u {
    struct {
        unsigned int cmdpp_illegal_opcode_int0:1;/* CMDPP0 has seen an illegal opcode.  0 = NOT_PENDING 1 = PENDING */
        unsigned int cmdpp_illegal_opcode_int1:1;/* CMDPP1 has seen an illegal opcode.  0 = NOT_PENDING 1 = PENDING */
        unsigned int cmdpp_illegal_opcode_int2:1;/* CMDPP2 has seen an illegal opcode.  0 = NOT_PENDING 1 = PENDING */
        unsigned int cmdpp_illegal_opcode_int3:1;/* CMDPP3 has seen an illegal opcode.  0 = NOT_PENDING 1 = PENDING */
        unsigned int cmdpp_illegal_opcode_int4:1;/* CMDPP4 has seen an illegal opcode.  0 = NOT_PENDING 1 = PENDING */
        unsigned int cmdpp_illegal_opcode_int5:1;/* CMDPP5 has seen an illegal opcode.  0 = NOT_PENDING 1 = PENDING */
        unsigned int cmdpp_illegal_opcode_int6:1;/* CMDPP6 has seen an illegal opcode.  0 = NOT_PENDING 1 = PENDING */
        unsigned int cmdpp_illegal_opcode_int7:1;/* CMDPP7 has seen an illegal opcode.  0 = NOT_PENDING 1 = PENDING */
        unsigned int undefined_bits_8_29:22;
        unsigned int ip_read_int:1;         /* Read transaction timeout occured after IP_BUSY_TIMEOUT cycles. Offending address in IP_READ_TIMEOUT_ADDR. 0 = NOT_PENDING 1 = PENDING */
        unsigned int ip_write_int:1;        /* Write transaction timeout occured after IP_BUSY_TIMEOUT cycles. Offending address in IP_WRITE_TIMEOUT_ADDR. 0 = NOT_PENDING 1 = PENDING */
    };

    uint32_t reg32;
} hintstatus_ext_t;

#define HINTMASK_EXT_OFFSET 0x2C
#define HINTMASK_EXT_RESET  0x00000000
typedef union hintmask_ext_u {
    struct {
        unsigned int cmdpp_illegal_opcode_intmask0:1;/* Mask CMDPP_ILLEGAL_OPCODE_INT0 interrupt bit. 0 = DISABLE 1 = ENABLE */
        unsigned int cmdpp_illegal_opcode_intmask1:1;/* See CMDPP_ILLEGAL_OPCODE_INTMASK0 0 = DISABLE 1 = ENABLE */
        unsigned int cmdpp_illegal_opcode_intmask2:1;/* See CMDPP_ILLEGAL_OPCODE_INTMASK0 0 = DISABLE 1 = ENABLE */
        unsigned int cmdpp_illegal_opcode_intmask3:1;/* See CMDPP_ILLEGAL_OPCODE_INTMASK0 0 = DISABLE 1 = ENABLE */
        unsigned int cmdpp_illegal_opcode_intmask4:1;/* See CMDPP_ILLEGAL_OPCODE_INTMASK0 0 = DISABLE 1 = ENABLE */
        unsigned int cmdpp_illegal_opcode_intmask5:1;/* See CMDPP_ILLEGAL_OPCODE_INTMASK0 0 = DISABLE 1 = ENABLE */
        unsigned int cmdpp_illegal_opcode_intmask6:1;/* See CMDPP_ILLEGAL_OPCODE_INTMASK0 0 = DISABLE 1 = ENABLE */
        unsigned int cmdpp_illegal_opcode_intmask7:1;/* See CMDPP_ILLEGAL_OPCODE_INTMASK0 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_8_29:22;
        unsigned int ip_read_intmask:1;     /* 0 = DISABLE 1 = ENABLE */
        unsigned int ip_write_intmask:1;    /* 0 = DISABLE 1 = ENABLE */
    };

    uint32_t reg32;
} hintmask_ext_t;

#define SYNCPT_THRESH_CPU0_INT_STATUS_OFFSET 0x40
#define SYNCPT_THRESH_CPU0_INT_STATUS_RESET  0x00000000
typedef union syncpt_thresh_cpu0_int_status_u {
    struct {
        unsigned int syncpt_thresh_cpu0_int_status_0:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_1:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_2:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_3:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_4:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_5:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_6:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_7:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_8:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_9:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_10:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_11:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_12:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_13:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_14:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_15:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_16:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_17:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_18:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_19:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_20:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_21:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_22:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_23:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_24:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_25:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_26:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_27:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_28:1;/* 0 = NOT_PENDING; 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_29:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_30:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu0_int_status_31:1;/* 0 = NOT_PENDING 1 = PENDING */
    };

    uint32_t reg32;
} syncpt_thresh_cpu0_int_status_t;

#define SYNCPT_THRESH_CPU1_INT_STATUS_OFFSET 0x48
#define SYNCPT_THRESH_CPU1_INT_STATUS_RESET  0x00000000
typedef union syncpt_thresh_cpu1_int_status_u {
    struct {
        unsigned int syncpt_thresh_cpu1_int_status_0:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_1:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_2:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_3:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_4:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_5:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_6:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_7:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_8:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_9:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_10:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_11:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_12:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_13:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_14:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_15:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_16:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_17:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_18:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_19:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_20:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_21:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_22:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_23:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_24:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_25:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_26:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_27:1;/* 0 = NOT_PENDING; 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_28:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_29:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_30:1;/* 0 = NOT_PENDING 1 = PENDING */
        unsigned int syncpt_thresh_cpu1_int_status_31:1;/* 0 = NOT_PENDING 1 = PENDING */
    };

    uint32_t reg32;
} syncpt_thresh_cpu1_int_status_t;

#define SYNCPT_THRESH_INT_MASK_OFFSET 0x50
#define SYNCPT_THRESH_INT_MASK_RESET  0x00000000
typedef union syncpt_thresh_int_mask_u {
    struct {
        unsigned int syncpt_thresh_int_mask_0:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_1:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_2:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_3:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_4:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_5:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_6:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_7:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_8:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_9:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_10:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_11:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_12:2;/* 0 = DISABLE 1 = ENABLE_CPU0; 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_13:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_14:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_15:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
    };

    uint32_t reg32;
} syncpt_thresh_int_mask_t;

#define SYNCPT_THRESH_INT_MASK_1_OFFSET 0x54
#define SYNCPT_THRESH_INT_MASK_1_RESET  0x00000000
typedef union syncpt_thresh_int_mask_1_u {
    struct {
        unsigned int syncpt_thresh_int_mask_16:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_17:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_18:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_19:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_20:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_21:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_22:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_23:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_24:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_25:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_26:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_27:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_28:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_29:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_30:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_mask_31:2;/* 0 = DISABLE 1 = ENABLE_CPU0 2 = ENABLE_CPU1 */
    };

    uint32_t reg32;
} syncpt_thresh_int_mask_1_t;

#define SYNCPT_THRESH_INT_DISABLE_OFFSET 0x60
#define SYNCPT_THRESH_INT_DISABLE_RESET  0x00000000
typedef union syncpt_thresh_int_disable_u {
    struct {
        unsigned int syncpt_thresh_int_disable_0:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_1:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_2:1;/* 0 = NO_CHANGE; 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_3:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_4:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_5:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_6:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_7:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_8:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_9:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_10:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_11:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_12:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_13:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_14:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_15:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_16:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_17:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_18:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_19:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_20:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_21:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_22:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_23:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_24:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_25:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_26:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_27:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_28:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_29:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_30:1;/* 0 = NO_CHANGE 1 = DISABLE */
        unsigned int syncpt_thresh_int_disable_31:1;/* 0 = NO_CHANGE 1 = DISABLE */
    };

    uint32_t reg32;
} syncpt_thresh_int_disable_t;

#define SYNCPT_THRESH_INT_ENABLE_CPU0_OFFSET 0x68
#define SYNCPT_THRESH_INT_ENABLE_CPU0_RESET  0x00000000
typedef union syncpt_thresh_int_enable_cpu0_u {
    struct {
        unsigned int syncpt_thresh_int_enable_cpu0_0:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_1:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_2:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_3:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_4:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_5:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_6:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_7:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_8:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_9:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_10:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_11:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_12:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_13:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_14:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_15:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_16:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_17:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_18:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_19:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_20:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_21:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_22:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_23:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_24:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_25:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_26:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_27:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_28:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_29:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_30:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
        unsigned int syncpt_thresh_int_enable_cpu0_31:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU0 */
    };

    uint32_t reg32;
} syncpt_thresh_int_enable_cpu0_t;

#define SYNCPT_THRESH_INT_ENABLE_CPU1_OFFSET 0x70
#define SYNCPT_THRESH_INT_ENABLE_CPU1_RESET  0x00000000
typedef union syncpt_thresh_int_enable_cpu1_u {
    struct {
        unsigned int syncpt_thresh_int_enable_cpu1_0:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_1:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_2:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_3:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_4:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_5:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_6:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_7:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_8:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_9:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_10:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_11:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_12:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_13:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_14:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_15:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_16:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_17:1;/* 0 = NO_CHANGE; 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_18:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_19:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_20:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_21:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_22:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_23:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_24:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_25:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_26:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_27:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_28:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_29:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_30:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
        unsigned int syncpt_thresh_int_enable_cpu1_31:1;/* 0 = NO_CHANGE 1 = ENABLE_CPU1 */
    };

    uint32_t reg32;
} syncpt_thresh_int_enable_cpu1_t;

#define CF0_SETUP_OFFSET 0x80
#define CF0_SETUP_RESET  0x003F0000
typedef union cf_setup_u {
    struct {
        unsigned int cf_base:9;            /* Channel 0 FIFO base */
        unsigned int undefined_bits_9_15:7;
        unsigned int cf_limit:9;           /* Channel 0 FIFO limit (highest address) */
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cf_setup_t;

#define CF1_SETUP_OFFSET 0x84
#define CF1_SETUP_RESET  0x007F0040
typedef union cf1_setup_u {
    struct {
        unsigned int cf1_base:9;            /* Channel 1 FIFO base */
        unsigned int undefined_bits_9_15:7;
        unsigned int cf1_limit:9;           /* Channel 1 FIFO limit (highest address) */
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cf1_setup_t;

#define CF2_SETUP_OFFSET 0x88
#define CF2_SETUP_RESET  0x00BF0080
typedef union cf2_setup_u {
    struct {
        unsigned int cf2_base:9;            /* Channel 2 FIFO base */
        unsigned int undefined_bits_9_15:7;
        unsigned int cf2_limit:9;           /* Channel 2 FIFO limit (highest address) */
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cf2_setup_t;

#define CF3_SETUP_OFFSET 0x8C
#define CF3_SETUP_RESET  0x00FF00C0
typedef union cf3_setup_u {
    struct {
        unsigned int cf3_base:9;            /* Channel 3 FIFO base */
        unsigned int undefined_bits_9_15:7;
        unsigned int cf3_limit:9;           /* Channel 3 FIFO limit (highest address) */
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cf3_setup_t;

#define CF4_SETUP_OFFSET 0x90
#define CF4_SETUP_RESET  0x013F0100
typedef union cf4_setup_u {
    struct {
        unsigned int cf4_base:9;            /* Channel 4 FIFO base */
        unsigned int undefined_bits_9_15:7;
        unsigned int cf4_limit:9;           /* Channel 4 FIFO limit (highest address) */
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cf4_setup_t;

#define CF5_SETUP_OFFSET 0x94
#define CF5_SETUP_RESET  0x017F0140
typedef union cf5_setup_u {
    struct {
        unsigned int cf5_base:9;            /* Channel 5 FIFO base */
        unsigned int undefined_bits_9_15:7;
        unsigned int cf5_limit:9;           /* Channel 5 FIFO limit (highest address) */
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cf5_setup_t;

#define CF6_SETUP_OFFSET 0x98
#define CF6_SETUP_RESET  0x01BF0180
typedef union cf6_setup_u {
    struct {
        unsigned int cf6_base:9;            /* Channel 6 FIFO base */
        unsigned int undefined_bits_9_15:7;
        unsigned int cf6_limit:9;           /* Channel 6 FIFO limit (highest address) */
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cf6_setup_t;

#define CF7_SETUP_OFFSET 0x9C
#define CF7_SETUP_RESET  0x01FF01C0
typedef union cf7_setup_u {
    struct {
        unsigned int cf7_base:9;            /* Channel 7 FIFO base */
        unsigned int undefined_bits_9_15:7;
        unsigned int cf7_limit:9;           /* Channel 7 FIFO limit (highest address) */
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cf7_setup_t;

#define CF_SETUPDONE_OFFSET 0xA0
#define CF_SETUPDONE_RESET  0x00000000
typedef union cf_setupdone_u {
    struct {
        unsigned int cf_setupdone:1;        /* Dummy bit */
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} cf_setupdone_t;

#define CMDPROC_CTRL_OFFSET 0xA4
#define CMDPROC_CTRL_RESET  0x00000000
typedef union cmdproc_ctrl_u {
    struct {
        unsigned int undefined_bit_0:1;
        unsigned int drop_illegal_opcodes:1;
        unsigned int gather_parse_disabled:1;
        unsigned int undefined_bits_3_4:2;
        unsigned int intfc_clken_ovr:1;
        unsigned int undefined_bits_6_31:26;
    };

    uint32_t reg32;
} cmdproc_ctrl_t;

#define CMDPROC_STAT_OFFSET 0xA8
#define CMDPROC_STAT_RESET  0x00000000
typedef union cmdproc_stat_u {
    struct {
        unsigned int illegal_opcode:8;
        unsigned int undefined_bits_8_31:24;
    };

    uint32_t reg32;
} cmdproc_stat_t;

#define CMDPROC_STOP_OFFSET 0xAC
#define CMDPROC_STOP_RESET  0x00000000
typedef union cmdproc_stop_u {
    struct {
        unsigned int ch0_cmdproc_stop:1;
        unsigned int ch1_cmdproc_stop:1;
        unsigned int ch2_cmdproc_stop:1;
        unsigned int ch3_cmdproc_stop:1;
        unsigned int ch4_cmdproc_stop:1;
        unsigned int ch5_cmdproc_stop:1;    /* 0 = RUN 1 = STOP */
        unsigned int ch6_cmdproc_stop:1;    /* 0 = RUN 1 = STOP */
        unsigned int ch7_cmdproc_stop:1;    /* 0 = RUN 1 = STOP */
        unsigned int undefined_bits_8_31:24;
    };

    uint32_t reg32;
} cmdproc_stop_t;

#define CH_TEARDOWN_OFFSET 0xB0
#define CH_TEARDOWN_RESET  0x00000000
typedef union ch_teardown_u {
    struct {
        unsigned int ch0_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int ch1_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int ch2_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int ch3_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int ch4_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int ch5_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int ch6_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int ch7_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int undefined_bits_8_31:24;
    };

    uint32_t reg32;
} ch_teardown_t;

#define MOD_TEARDOWN_OFFSET 0xB4
#define MOD_TEARDOWN_RESET  0x00000000
typedef union mod_teardown_u {
    struct {
        unsigned int undefined_bit_0:1;
        unsigned int mpe_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int vi_teardown:1;         /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int epp_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int isp_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int gr2d_teardown:1;       /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int gr3d_teardown:1;       /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int undefined_bit_7:1;
        unsigned int display_teardown:1;    /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int displayb_teardown:1;   /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int hdmi_teardown:1;       /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int tvo_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int dsi_teardown:1;        /* 0 = NO_ACTION 1 = TEARDOWN */
        unsigned int undefined_bits_13_31:19;
    };

    uint32_t reg32;
} mod_teardown_t;

#define CH0_STATUS_OFFSET 0xB8
#define CH0_STATUS_RESET  0x00000000
typedef union ch_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int chout_class:10;       /* Current or blocked (requested) class for channel 0 */
        unsigned int undefined_bits_26_30:5;
        unsigned int ctxsw_pending:1;
    };

    uint32_t reg32;
} ch_status_t;

#define CH1_STATUS_OFFSET 0xBC
#define CH1_STATUS_RESET  0x00000000
typedef union ch1_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int chout_class1:10;       /* Current or blocked (requested) class for channel 1 */
        unsigned int undefined_bits_26_30:5;
        unsigned int ctxsw_pending1:1;
    };

    uint32_t reg32;
} ch1_status_t;

#define CH2_STATUS_OFFSET 0xC0
#define CH2_STATUS_RESET  0x00000000
typedef union ch2_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int chout_class2:10;       /* Current or blocked (requested) class for channel 2 */
        unsigned int undefined_bits_26_30:5;
        unsigned int ctxsw_pending2:1;
    };

    uint32_t reg32;
} ch2_status_t;

#define CH3_STATUS_OFFSET 0xC4
#define CH3_STATUS_RESET  0x00000000
typedef union ch3_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int chout_class3:10;       /* Current or blocked (requested) class for channel 3 */
        unsigned int undefined_bits_26_30:5;
        unsigned int ctxsw_pending3:1;
    };

    uint32_t reg32;
} ch3_status_t;

#define CH4_STATUS_OFFSET 0xC8
#define CH4_STATUS_RESET  0x00000000
typedef union ch4_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int chout_class4:10;       /* Current or blocked (requested) class for channel 4 */
        unsigned int undefined_bits_26_30:5;
        unsigned int ctxsw_pending4:1;
    };

    uint32_t reg32;
} ch4_status_t;

#define CH5_STATUS_OFFSET 0xCC
#define CH5_STATUS_RESET  0x00000000
typedef union ch5_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int chout_class5:10;       /* Current or blocked (requested) class for channel 5 */
        unsigned int undefined_bits_26_30:5;
        unsigned int ctxsw_pending5:1;
    };

    uint32_t reg32;
} ch5_status_t;

#define CH6_STATUS_OFFSET 0xD0
#define CH6_STATUS_RESET  0x00000000
typedef union ch6_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int chout_class6:10;       /* Current or blocked (requested) class for channel 6 */
        unsigned int undefined_bits_26_30:5;
        unsigned int ctxsw_pending6:1;
    };

    uint32_t reg32;
} ch6_status_t;

#define CH7_STATUS_OFFSET 0xD4
#define CH7_STATUS_RESET  0x00000000
typedef union ch7_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int chout_class7:10;       /* Current or blocked (requested) class for channel 7 */
        unsigned int undefined_bits_26_30:5;
        unsigned int ctxsw_pending7:1;
    };

    uint32_t reg32;
} ch7_status_t;

#define DISPLAY_STATUS_OFFSET 0xD8
#define DISPLAY_STATUS_RESET  0x00000000
typedef union display_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int display_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} display_status_t;

#define DISPLAYB_STATUS_OFFSET 0xDC
#define DISPLAYB_STATUS_RESET  0x00000000
typedef union displayb_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int displayb_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} displayb_status_t;

#define EPP_STATUS_OFFSET 0xE0
#define EPP_STATUS_RESET  0x00000000
typedef union epp_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int epp_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} epp_status_t;

#define GR3D_STATUS_OFFSET 0xE4
#define GR3D_STATUS_RESET  0x00000000
typedef union gr3d_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int gr3d_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} gr3d_status_t;

#define ISP_STATUS_OFFSET 0xE8
#define ISP_STATUS_RESET  0x00000000
typedef union isp_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int isp_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} isp_status_t;

#define MPE_STATUS_OFFSET 0xEC
#define MPE_STATUS_RESET  0x00000000
typedef union mpe_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int mpe_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} mpe_status_t;

#define TVO_STATUS_OFFSET 0xF0
#define TVO_STATUS_RESET  0x00000000
typedef union tvo_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int tvo_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} tvo_status_t;

#define DSI_STATUS_OFFSET 0xF4
#define DSI_STATUS_RESET  0x00000000
typedef union dsi_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int dsi_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} dsi_status_t;

#define HDMI_STATUS_OFFSET 0xF8
#define HDMI_STATUS_RESET  0x00000000
typedef union hdmi_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int hdmi_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} hdmi_status_t;

#define VI_STATUS_OFFSET 0xFC
#define VI_STATUS_RESET  0x00000000
typedef union vi_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int vi_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} vi_status_t;

#define GR2D_STATUS_OFFSET 0x100
#define GR2D_STATUS_RESET  0x00000000
typedef union gr2d_status_u {
    struct {
        unsigned int undefined_bits_0_15:16;
        unsigned int gr2d_currcl:10;
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} gr2d_status_t;

#define DIRECT_MODULE_CONFIG_OFFSET 0x1A0
#define DIRECT_MODULE_CONFIG_RESET  0x15000000
typedef union direct_module_config_u {
    struct {
        unsigned int undefined_bits_0_1:2;
        unsigned int base:30;
    };

    uint32_t reg32;
} direct_module_config_t;

#define USEC_CLK_OFFSET 0x1A4
#define USEC_CLK_RESET  0x0000015E
typedef union usec_clk_u {
    struct {
        unsigned int usec_clks:12;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} usec_clk_t;

#define CTXSW_TIMEOUT_CFG_OFFSET 0x1A8
#define CTXSW_TIMEOUT_CFG_RESET  0x0000000F
typedef union ctxsw_timeout_cfg_u {
    struct {
        unsigned int wait_ctxsw_cnt:8;      /* # of cycles to wait */
        unsigned int undefined_bits_8_31:24;
    };

    uint32_t reg32;
} ctxsw_timeout_cfg_t;

#define INDREG_DMA_CTRL_OFFSET 0x1AC
#define INDREG_DMA_CTRL_RESET  0x00000000
typedef union indreg_dma_ctrl_u {
    struct {
        unsigned int ahbdma_chid:4;         /* channel being used by indirect rd for dma (which chout FIFO to monitor) */
        unsigned int undefined_bit_4:1;
        unsigned int ahbdma_attn_lvl:2;     /* # of entries to rx'd before sending dma req, 1, 4, or 8 */
        unsigned int ahbdma_enable:1;       /* enable generation of req to dma engine  0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_8_31:24;
    };

    uint32_t reg32;
} indreg_dma_ctrl_t;

#define CHANNEL_PRIORITY_OFFSET 0x1B0
#define CHANNEL_PRIORITY_RESET  0x00000000
typedef union channel_priority_u {
    struct {
        unsigned int hipri_ch0:1;           /* 0 = DISABLE 1 = ENABLE */
        unsigned int hipri_ch1:1;           /* 0 = DISABLE; 1 = ENABLE */
        unsigned int hipri_ch2:1;           /* 0 = DISABLE 1 = ENABLE */
        unsigned int hipri_ch3:1;           /* 0 = DISABLE 1 = ENABLE */
        unsigned int hipri_ch4:1;           /* 0 = DISABLE 1 = ENABLE */
        unsigned int hipri_ch5:1;           /* 0 = DISABLE 1 = ENABLE */
        unsigned int hipri_ch6:1;           /* 0 = DISABLE 1 = ENABLE */
        unsigned int hipri_ch7:1;           /* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_8_31:24;
    };

    uint32_t reg32;
} channel_priority_t;

#define CDMA_ASM_TIMEOUT_OFFSET 0x1B4
#define CDMA_ASM_TIMEOUT_RESET  0x00000404
typedef union cdma_asm_timeout_u {
    struct {
        unsigned int cdma_asm_dfifo_timeout:5;
        unsigned int undefined_bits_5_7:3;
        unsigned int cdma_asm_gfifo_timeout:5;
        unsigned int undefined_bits_13_31:19;
    };

    uint32_t reg32;
} cdma_asm_timeout_t;

#define CDMA_MISC_OFFSET 0x1B8
#define CDMA_MISC_RESET  0x00000000
typedef union cdma_misc_u {
    struct {
        unsigned int cdma_delay_put:6;
        unsigned int undefined_bits_6_7:2;
        unsigned int cdma_simple_prefetch:1;
        unsigned int cdma_put_sync_disable:1;
        unsigned int cdma_clken_ovr:1;
        unsigned int undefined_bits_11_31:21;
    };

    uint32_t reg32;
} cdma_misc_t;

#define IP_BUSY_TIMEOUT_OFFSET 0x1BC
#define IP_BUSY_TIMEOUT_RESET  0x00000000
typedef union ip_busy_timeout_u {
    struct {
        unsigned int ip_busy_timeout:16;    /* Number of busy cycles before requesting a retry. 0 = disabled */
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} ip_busy_timeout_t;

#define IP_READ_TIMEOUT_ADDR_OFFSET 0x1C0
#define IP_READ_TIMEOUT_ADDR_RESET  0x00000000
typedef union ip_read_timeout_addr_u {
    struct {
        unsigned int undefined_bits_0_1:2;
        unsigned int ip_read_timeout_addr:30;/* Address of transaction that caused an AXI read timeout */
    };

    uint32_t reg32;
} ip_read_timeout_addr_t;

#define IP_WRITE_TIMEOUT_ADDR_OFFSET 0x1C4
#define IP_WRITE_TIMEOUT_ADDR_RESET  0x00000000
typedef union ip_write_timeout_addr_u {
    struct {
        unsigned int undefined_bits_0_1:2;
        unsigned int ip_write_timeout_addr:30;/* Address of transaction that caused an AXI write timeout */
    };

    uint32_t reg32;
} ip_write_timeout_addr_t;

#define MCCIF_THCTRL_OFFSET 0x1D8
#define MCCIF_THCTRL_RESET  0x00000000
#define MCCIF_THCTRL_WRMASK 0xFFFFFFC0
typedef union mccif_thctrl_u {
    struct {
        unsigned int csw_host1xw_fifostat:6;
        unsigned int undefined_bits_6_7:2;
        unsigned int csw_host1xw2mc_hpth:6;
        unsigned int undefined_bits_14_31:18;
    };

    uint32_t reg32;
} mccif_thctrl_t;

#define HC_MCCIF_FIFOCTRL_OFFSET 0x1DC
#define HC_MCCIF_FIFOCTRL_RESET  0x00000000
typedef union hc_mccif_fifoctrl_u {
    struct {
        unsigned int hc_mccif_wrcl_mcle2x:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int hc_mccif_rdmc_rdfast:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int hc_mccif_wrmc_clle2x:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int hc_mccif_rdcl_rdfast:1;/* 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_4_31:28;
    };

    uint32_t reg32;
} hc_mccif_fifoctrl_t;

#define TIMEOUT_WCOAL_HC_OFFSET 0x1E0
#define TIMEOUT_WCOAL_HC_RESET  0x00000032
typedef union timeout_wcoal_hc_u {
    struct {
        unsigned int host1xw_wcoal_tmval:8;
        unsigned int undefined_bits_8_31:24;
    };

    uint32_t reg32;
} timeout_wcoal_hc_t;

#define HWLOCK0_OFFSET 0x280
#define HWLOCK0_RESET  0x00000000
typedef union hwlock_u {
    struct {
        unsigned int hwlock:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} hwlock_t;

#define HWLOCK1_OFFSET 0x284
#define HWLOCK1_RESET  0x00000000
typedef union hwlock1_u {
    struct {
        unsigned int hwlock1:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} hwlock1_t;

#define HWLOCK2_OFFSET 0x288
#define HWLOCK2_RESET  0x00000000
typedef union hwlock2_u {
    struct {
        unsigned int hwlock2:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} hwlock2_t;

#define HWLOCK3_OFFSET 0x28C
#define HWLOCK3_RESET  0x00000000
typedef union hwlock3_u {
    struct {
        unsigned int hwlock3:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} hwlock3_t;

#define HWLOCK4_OFFSET 0x290
#define HWLOCK4_RESET  0x00000000
typedef union hwlock4_u {
    struct {
        unsigned int hwlock4:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} hwlock4_t;

#define HWLOCK5_OFFSET 0x294
#define HWLOCK5_RESET  0x00000000
typedef union hwlock5_u {
    struct {
        unsigned int hwlock5:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} hwlock5_t;

#define HWLOCK6_OFFSET 0x298
#define HWLOCK6_RESET  0x00000000
typedef union hwlock6_u {
    struct {
        unsigned int hwlock6:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} hwlock6_t;

#define HWLOCK7_OFFSET 0x29C
#define HWLOCK7_RESET  0x00000000
typedef union hwlock7_u {
    struct {
        unsigned int hwlock7:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} hwlock7_t;

#define MLOCK_OFFSET 0x2C0
#define MLOCK_RESET  0x00000000
typedef union mlock_u {
    struct {
        unsigned int mlock:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_t;

#define MLOCK_1_OFFSET 0x2C4
#define MLOCK_1_RESET  0x00000000
typedef union mlock_1_u {
    struct {
        unsigned int mlock_1:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_1_t;

#define MLOCK_2_OFFSET 0x2C8
#define MLOCK_2_RESET  0x00000000
typedef union mlock_2_u {
    struct {
        unsigned int mlock_2:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_2_t;

#define MLOCK_3_OFFSET 0x2CC
#define MLOCK_3_RESET  0x00000000
typedef union mlock_3_u {
    struct {
        unsigned int mlock_3:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_3_t;

#define MLOCK_4_OFFSET 0x2D0
#define MLOCK_4_RESET  0x00000000
typedef union mlock_4_u {
    struct {
        unsigned int mlock_4:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_4_t;

#define MLOCK_5_OFFSET 0x2D4
#define MLOCK_5_RESET  0x00000000
typedef union mlock_5_u {
    struct {
        unsigned int mlock_5:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_5_t;

#define MLOCK_6_OFFSET 0x2D8
#define MLOCK_6_RESET  0x00000000
typedef union mlock_6_u {
    struct {
        unsigned int mlock_6:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_6_t;

#define MLOCK_7_OFFSET 0x2DC
#define MLOCK_7_RESET  0x00000000
typedef union mlock_7_u {
    struct {
        unsigned int mlock_7:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_7_t;

#define MLOCK_8_OFFSET 0x2E0
#define MLOCK_8_RESET  0x00000000
typedef union mlock_8_u {
    struct {
        unsigned int mlock_8:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_8_t;

#define MLOCK_9_OFFSET 0x2E4
#define MLOCK_9_RESET  0x00000000
typedef union mlock_9_u {
    struct {
        unsigned int mlock_9:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_9_t;

#define MLOCK_10_OFFSET 0x2E8
#define MLOCK_10_RESET  0x00000000
typedef union mlock_10_u {
    struct {
        unsigned int mlock_10:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_10_t;

#define MLOCK_11_OFFSET 0x2EC
#define MLOCK_11_RESET  0x00000000
typedef union mlock_11_u {
    struct {
        unsigned int mlock_11:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_11_t;

#define MLOCK_12_OFFSET 0x2F0
#define MLOCK_12_RESET  0x00000000
typedef union mlock_12_u {
    struct {
        unsigned int mlock_12:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_12_t;

#define MLOCK_13_OFFSET 0x2F4
#define MLOCK_13_RESET  0x00000000
typedef union mlock_13_u {
    struct {
        unsigned int mlock_13:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_13_t;

#define MLOCK_14_OFFSET 0x2F8
#define MLOCK_14_RESET  0x00000000
typedef union mlock_14_u {
    struct {
        unsigned int mlock_14:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_14_t;

#define MLOCK_15_OFFSET 0x2FC
#define MLOCK_15_RESET  0x00000000
typedef union mlock_15_u {
    struct {
        unsigned int mlock_15:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} mlock_15_t;

#define MLOCK_OWNER_OFFSET 0x340
#define MLOCK_OWNER_RESET  0x00000000
typedef union mlock_owner_u {
    struct {
        unsigned int mlock_ch_owns:1;
        unsigned int mlock_cpu_owns:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_t;

#define MLOCK_OWNER_1_OFFSET 0x344
#define MLOCK_OWNER_1_RESET  0x00000000
typedef union mlock_owner_1_u {
    struct {
        unsigned int mlock_ch_owns_1:1;
        unsigned int mlock_cpu_owns_1:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_1:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_1_t;

#define MLOCK_OWNER_2_OFFSET 0x348
#define MLOCK_OWNER_2_RESET  0x00000000
typedef union mlock_owner_2_u {
    struct {
        unsigned int mlock_ch_owns_2:1;
        unsigned int mlock_cpu_owns_2:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_2:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_2_t;

#define MLOCK_OWNER_3_OFFSET 0x34C
#define MLOCK_OWNER_3_RESET  0x00000000
typedef union mlock_owner_3_u {
    struct {
        unsigned int mlock_ch_owns_3:1;
        unsigned int mlock_cpu_owns_3:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_3:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_3_t;

#define MLOCK_OWNER_4_OFFSET 0x350
#define MLOCK_OWNER_4_RESET  0x00000000
typedef union mlock_owner_4_u {
    struct {
        unsigned int mlock_ch_owns_4:1;
        unsigned int mlock_cpu_owns_4:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_4:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_4_t;

#define MLOCK_OWNER_5_OFFSET 0x354
#define MLOCK_OWNER_5_RESET  0x00000000
typedef union mlock_owner_5_u {
    struct {
        unsigned int mlock_ch_owns_5:1;
        unsigned int mlock_cpu_owns_5:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_5:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_5_t;

#define MLOCK_OWNER_6_OFFSET 0x358
#define MLOCK_OWNER_6_RESET  0x00000000
typedef union mlock_owner_6_u {
    struct {
        unsigned int mlock_ch_owns_6:1;
        unsigned int mlock_cpu_owns_6:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_6:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_6_t;

#define MLOCK_OWNER_7_OFFSET 0x35C
#define MLOCK_OWNER_7_RESET  0x00000000
typedef union mlock_owner_7_u {
    struct {
        unsigned int mlock_ch_owns_7:1;
        unsigned int mlock_cpu_owns_7:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_7:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_7_t;

#define MLOCK_OWNER_8_OFFSET 0x360
#define MLOCK_OWNER_8_RESET  0x00000000
typedef union mlock_owner_8_u {
    struct {
        unsigned int mlock_ch_owns_8:1;
        unsigned int mlock_cpu_owns_8:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_8:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_8_t;

#define MLOCK_OWNER_9_OFFSET 0x364
#define MLOCK_OWNER_9_RESET  0x00000000
typedef union mlock_owner_9_u {
    struct {
        unsigned int mlock_ch_owns_9:1;
        unsigned int mlock_cpu_owns_9:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_9:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_9_t;

#define MLOCK_OWNER_10_OFFSET 0x368
#define MLOCK_OWNER_10_RESET  0x00000000
typedef union mlock_owner_10_u {
    struct {
        unsigned int mlock_ch_owns_10:1;
        unsigned int mlock_cpu_owns_10:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_10:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_10_t;

#define MLOCK_OWNER_11_OFFSET 0x36C
#define MLOCK_OWNER_11_RESET  0x00000000
typedef union mlock_owner_11_u {
    struct {
        unsigned int mlock_ch_owns_11:1;
        unsigned int mlock_cpu_owns_11:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_11:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_11_t;

#define MLOCK_OWNER_12_OFFSET 0x370
#define MLOCK_OWNER_12_RESET  0x00000000
typedef union mlock_owner_12_u {
    struct {
        unsigned int mlock_ch_owns_12:1;
        unsigned int mlock_cpu_owns_12:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_12:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_12_t;

#define MLOCK_OWNER_13_OFFSET 0x374
#define MLOCK_OWNER_13_RESET  0x00000000
typedef union mlock_owner_13_u {
    struct {
        unsigned int mlock_ch_owns_13:1;
        unsigned int mlock_cpu_owns_13:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_13:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_13_t;

#define MLOCK_OWNER_14_OFFSET 0x378
#define MLOCK_OWNER_14_RESET  0x00000000
typedef union mlock_owner_14_u {
    struct {
        unsigned int mlock_ch_owns_14:1;
        unsigned int mlock_cpu_owns_14:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_14:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_14_t;

#define MLOCK_OWNER_15_OFFSET 0x37C
#define MLOCK_OWNER_15_RESET  0x00000000
typedef union mlock_owner_15_u {
    struct {
        unsigned int mlock_ch_owns_15:1;
        unsigned int mlock_cpu_owns_15:1;
        unsigned int undefined_bits_2_7:6;
        unsigned int mlock_owner_chid_15:4;
        unsigned int undefined_bits_12_31:20;
    };

    uint32_t reg32;
} mlock_owner_15_t;

#define MLOCK_ERROR_OFFSET 0x3C0
#define MLOCK_ERROR_RESET  0x00000000
typedef union mlock_error_u {
    struct {
        unsigned int mlock_error_0:1;
        unsigned int mlock_error_1:1;
        unsigned int mlock_error_2:1;
        unsigned int mlock_error_3:1;
        unsigned int mlock_error_4:1;
        unsigned int mlock_error_5:1;
        unsigned int mlock_error_6:1;
        unsigned int mlock_error_7:1;
        unsigned int mlock_error_8:1;
        unsigned int mlock_error_9:1;
        unsigned int mlock_error_10:1;
        unsigned int mlock_error_11:1;
        unsigned int mlock_error_12:1;
        unsigned int mlock_error_13:1;
        unsigned int mlock_error_14:1;
        unsigned int mlock_error_15:1;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} mlock_error_t;

#define SYNCPT_OFFSET 0x400
#define SYNCPT_RESET  0x00000000
typedef union syncpt_u {
    struct {
        unsigned int syncpt_0:32;
    };

    uint32_t reg32;
} syncpt_t;

#define SYNCPT_1_OFFSET 0x404
#define SYNCPT_1_RESET  0x00000000
typedef union syncpt_1_u {
    struct {
        unsigned int syncpt_1:32;
    };

    uint32_t reg32;
} syncpt_1_t;

#define SYNCPT_2_OFFSET 0x408
#define SYNCPT_2_RESET  0x00000000
typedef union syncpt_2_u {
    struct {
        unsigned int syncpt_2:32;
    };

    uint32_t reg32;
} syncpt_2_t;

#define SYNCPT_3_OFFSET 0x40C
#define SYNCPT_3_RESET  0x00000000
typedef union syncpt_3_u {
    struct {
        unsigned int syncpt_3:32;
    };

    uint32_t reg32;
} syncpt_3_t;

#define SYNCPT_4_OFFSET 0x410
#define SYNCPT_4_RESET  0x00000000
typedef union syncpt_4_u {
    struct {
        unsigned int syncpt_4:32;
    };

    uint32_t reg32;
} syncpt_4_t;

#define SYNCPT_5_OFFSET 0x414
#define SYNCPT_5_RESET  0x00000000
typedef union syncpt_5_u {
    struct {
        unsigned int syncpt_5:32;
    };

    uint32_t reg32;
} syncpt_5_t;

#define SYNCPT_6_OFFSET 0x418
#define SYNCPT_6_RESET  0x00000000
typedef union syncpt_6_u {
    struct {
        unsigned int syncpt_6:32;
    };

    uint32_t reg32;
} syncpt_6_t;

#define SYNCPT_7_OFFSET 0x41C
#define SYNCPT_7_RESET  0x00000000
typedef union syncpt_7_u {
    struct {
        unsigned int syncpt_7:32;
    };

    uint32_t reg32;
} syncpt_7_t;

#define SYNCPT_8_OFFSET 0x420
#define SYNCPT_8_RESET  0x00000000
typedef union syncpt_8_u {
    struct {
        unsigned int syncpt_8:32;
    };

    uint32_t reg32;
} syncpt_8_t;

#define SYNCPT_9_OFFSET 0x424
#define SYNCPT_9_RESET  0x00000000
typedef union syncpt_9_u {
    struct {
        unsigned int syncpt_9:32;
    };

    uint32_t reg32;
} syncpt_9_t;

#define SYNCPT_10_OFFSET 0x428
#define SYNCPT_10_RESET  0x00000000
typedef union syncpt_10_u {
    struct {
        unsigned int syncpt_10:32;
    };

    uint32_t reg32;
} syncpt_10_t;

#define SYNCPT_11_OFFSET 0x42C
#define SYNCPT_11_RESET  0x00000000
typedef union syncpt_11_u {
    struct {
        unsigned int syncpt_11:32;
    };

    uint32_t reg32;
} syncpt_11_t;

#define SYNCPT_12_OFFSET 0x430
#define SYNCPT_12_RESET  0x00000000
typedef union syncpt_12_u {
    struct {
        unsigned int syncpt_12:32;
    };

    uint32_t reg32;
} syncpt_12_t;

#define SYNCPT_13_OFFSET 0x434
#define SYNCPT_13_RESET  0x00000000
typedef union syncpt_13_u {
    struct {
        unsigned int syncpt_13:32;
    };

    uint32_t reg32;
} syncpt_13_t;

#define SYNCPT_14_OFFSET 0x438
#define SYNCPT_14_RESET  0x00000000
typedef union syncpt_14_u {
    struct {
        unsigned int syncpt_14:32;
    };

    uint32_t reg32;
} syncpt_14_t;

#define SYNCPT_15_OFFSET 0x43C
#define SYNCPT_15_RESET  0x00000000
typedef union syncpt_15_u {
    struct {
        unsigned int syncpt_15:32;
    };

    uint32_t reg32;
} syncpt_15_t;

#define SYNCPT_16_OFFSET 0x440
#define SYNCPT_16_RESET  0x00000000
typedef union syncpt_16_u {
    struct {
        unsigned int syncpt_16:32;
    };

    uint32_t reg32;
} syncpt_16_t;

#define SYNCPT_17_OFFSET 0x444
#define SYNCPT_17_RESET  0x00000000
typedef union syncpt_17_u {
    struct {
        unsigned int syncpt_17:32;
    };

    uint32_t reg32;
} syncpt_17_t;

#define SYNCPT_18_OFFSET 0x448
#define SYNCPT_18_RESET  0x00000000
typedef union syncpt_18_u {
    struct {
        unsigned int syncpt_18:32;
    };

    uint32_t reg32;
} syncpt_18_t;

#define SYNCPT_19_OFFSET 0x44C
#define SYNCPT_19_RESET  0x00000000
typedef union syncpt_19_u {
    struct {
        unsigned int syncpt_19:32;
    };

    uint32_t reg32;
} syncpt_19_t;

#define SYNCPT_20_OFFSET 0x450
#define SYNCPT_20_RESET  0x00000000
typedef union syncpt_20_u {
    struct {
        unsigned int syncpt_20:32;
    };

    uint32_t reg32;
} syncpt_20_t;

#define SYNCPT_21_OFFSET 0x454
#define SYNCPT_21_RESET  0x00000000
typedef union syncpt_21_u {
    struct {
        unsigned int syncpt_21:32;
    };

    uint32_t reg32;
} syncpt_21_t;

#define SYNCPT_22_OFFSET 0x458
#define SYNCPT_22_RESET  0x00000000
typedef union syncpt_22_u {
    struct {
        unsigned int syncpt_22:32;
    };

    uint32_t reg32;
} syncpt_22_t;

#define SYNCPT_23_OFFSET 0x45C
#define SYNCPT_23_RESET  0x00000000
typedef union syncpt_23_u {
    struct {
        unsigned int syncpt_23:32;
    };

    uint32_t reg32;
} syncpt_23_t;

#define SYNCPT_24_OFFSET 0x460
#define SYNCPT_24_RESET  0x00000000
typedef union syncpt_24_u {
    struct {
        unsigned int syncpt_24:32;
    };

    uint32_t reg32;
} syncpt_24_t;

#define SYNCPT_25_OFFSET 0x464
#define SYNCPT_25_RESET  0x00000000
typedef union syncpt_25_u {
    struct {
        unsigned int syncpt_25:32;
    };

    uint32_t reg32;
} syncpt_25_t;

#define SYNCPT_26_OFFSET 0x468
#define SYNCPT_26_RESET  0x00000000
typedef union syncpt_26_u {
    struct {
        unsigned int syncpt_26:32;
    };

    uint32_t reg32;
} syncpt_26_t;

#define SYNCPT_27_OFFSET 0x46C
#define SYNCPT_27_RESET  0x00000000
typedef union syncpt_27_u {
    struct {
        unsigned int syncpt_27:32;
    };

    uint32_t reg32;
} syncpt_27_t;

#define SYNCPT_28_OFFSET 0x470
#define SYNCPT_28_RESET  0x00000000
typedef union syncpt_28_u {
    struct {
        unsigned int syncpt_28:32;
    };

    uint32_t reg32;
} syncpt_28_t;

#define SYNCPT_29_OFFSET 0x474
#define SYNCPT_29_RESET  0x00000000
typedef union syncpt_29_u {
    struct {
        unsigned int syncpt_29:32;
    };

    uint32_t reg32;
} syncpt_29_t;

#define SYNCPT_30_OFFSET 0x478
#define SYNCPT_30_RESET  0x00000000
typedef union syncpt_30_u {
    struct {
        unsigned int syncpt_30:32;
    };

    uint32_t reg32;
} syncpt_30_t;

#define SYNCPT_31_OFFSET 0x47C
#define SYNCPT_31_RESET  0x00000000
typedef union syncpt_31_u {
    struct {
        unsigned int syncpt_31:32;
    };

    uint32_t reg32;
} syncpt_31_t;

#define SYNCPT_INT_THRESH_OFFSET 0x500
#define SYNCPT_INT_THRESH_RESET  0x00000000
typedef union syncpt_int_thresh_u {
    struct {
        unsigned int int_thresh:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_t;

#define SYNCPT_INT_THRESH_1_OFFSET 0x504
#define SYNCPT_INT_THRESH_1_RESET  0x00000000
typedef union syncpt_int_thresh_1_u {
    struct {
        unsigned int int_thresh_1:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_1_t;

#define SYNCPT_INT_THRESH_2_OFFSET 0x508
#define SYNCPT_INT_THRESH_2_RESET  0x00000000
typedef union syncpt_int_thresh_2_u {
    struct {
        unsigned int int_thresh_2:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_2_t;

#define SYNCPT_INT_THRESH_3_OFFSET 0x50C
#define SYNCPT_INT_THRESH_3_RESET  0x00000000
typedef union syncpt_int_thresh_3_u {
    struct {
        unsigned int int_thresh_3:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_3_t;

#define SYNCPT_INT_THRESH_4_OFFSET 0x510
#define SYNCPT_INT_THRESH_4_RESET  0x00000000
typedef union syncpt_int_thresh_4_u {
    struct {
        unsigned int int_thresh_4:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_4_t;

#define SYNCPT_INT_THRESH_5_OFFSET 0x514
#define SYNCPT_INT_THRESH_5_RESET  0x00000000
typedef union syncpt_int_thresh_5_u {
    struct {
        unsigned int int_thresh_5:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_5_t;

#define SYNCPT_INT_THRESH_6_OFFSET 0x518
#define SYNCPT_INT_THRESH_6_RESET  0x00000000
typedef union syncpt_int_thresh_6_u {
    struct {
        unsigned int int_thresh_6:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_6_t;

#define SYNCPT_INT_THRESH_7_OFFSET 0x51C
#define SYNCPT_INT_THRESH_7_RESET  0x00000000
typedef union syncpt_int_thresh_7_u {
    struct {
        unsigned int int_thresh_7:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_7_t;

#define SYNCPT_INT_THRESH_8_OFFSET 0x520
#define SYNCPT_INT_THRESH_8_RESET  0x00000000
typedef union syncpt_int_thresh_8_u {
    struct {
        unsigned int int_thresh_8:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_8_t;

#define SYNCPT_INT_THRESH_9_OFFSET 0x524
#define SYNCPT_INT_THRESH_9_RESET  0x00000000
typedef union syncpt_int_thresh_9_u {
    struct {
        unsigned int int_thresh_9:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_9_t;

#define SYNCPT_INT_THRESH_10_OFFSET 0x528
#define SYNCPT_INT_THRESH_10_RESET  0x00000000
typedef union syncpt_int_thresh_10_u {
    struct {
        unsigned int int_thresh_10:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_10_t;

#define SYNCPT_INT_THRESH_11_OFFSET 0x52C
#define SYNCPT_INT_THRESH_11_RESET  0x00000000
typedef union syncpt_int_thresh_11_u {
    struct {
        unsigned int int_thresh_11:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_11_t;

#define SYNCPT_INT_THRESH_12_OFFSET 0x530
#define SYNCPT_INT_THRESH_12_RESET  0x00000000
typedef union syncpt_int_thresh_12_u {
    struct {
        unsigned int int_thresh_12:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_12_t;

#define SYNCPT_INT_THRESH_13_OFFSET 0x534
#define SYNCPT_INT_THRESH_13_RESET  0x00000000
typedef union syncpt_int_thresh_13_u {
    struct {
        unsigned int int_thresh_13:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_13_t;

#define SYNCPT_INT_THRESH_14_OFFSET 0x538
#define SYNCPT_INT_THRESH_14_RESET  0x00000000
typedef union syncpt_int_thresh_14_u {
    struct {
        unsigned int int_thresh_14:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_14_t;

#define SYNCPT_INT_THRESH_15_OFFSET 0x53C
#define SYNCPT_INT_THRESH_15_RESET  0x00000000
typedef union syncpt_int_thresh_15_u {
    struct {
        unsigned int int_thresh_15:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_15_t;

#define SYNCPT_INT_THRESH_16_OFFSET 0x540
#define SYNCPT_INT_THRESH_16_RESET  0x00000000
typedef union syncpt_int_thresh_16_u {
    struct {
        unsigned int int_thresh_16:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_16_t;

#define SYNCPT_INT_THRESH_17_OFFSET 0x544
#define SYNCPT_INT_THRESH_17_RESET  0x00000000
typedef union syncpt_int_thresh_17_u {
    struct {
        unsigned int int_thresh_17:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_17_t;

#define SYNCPT_INT_THRESH_18_OFFSET 0x548
#define SYNCPT_INT_THRESH_18_RESET  0x00000000
typedef union syncpt_int_thresh_18_u {
    struct {
        unsigned int int_thresh_18:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_18_t;

#define SYNCPT_INT_THRESH_19_OFFSET 0x54C
#define SYNCPT_INT_THRESH_19_RESET  0x00000000
typedef union syncpt_int_thresh_19_u {
    struct {
        unsigned int int_thresh_19:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_19_t;

#define SYNCPT_INT_THRESH_20_OFFSET 0x550
#define SYNCPT_INT_THRESH_20_RESET  0x00000000
typedef union syncpt_int_thresh_20_u {
    struct {
        unsigned int int_thresh_20:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_20_t;

#define SYNCPT_INT_THRESH_21_OFFSET 0x554
#define SYNCPT_INT_THRESH_21_RESET  0x00000000
typedef union syncpt_int_thresh_21_u {
    struct {
        unsigned int int_thresh_21:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_21_t;

#define SYNCPT_INT_THRESH_22_OFFSET 0x558
#define SYNCPT_INT_THRESH_22_RESET  0x00000000
typedef union syncpt_int_thresh_22_u {
    struct {
        unsigned int int_thresh_22:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_22_t;

#define SYNCPT_INT_THRESH_23_OFFSET 0x55C
#define SYNCPT_INT_THRESH_23_RESET  0x00000000
typedef union syncpt_int_thresh_23_u {
    struct {
        unsigned int int_thresh_23:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_23_t;

#define SYNCPT_INT_THRESH_24_OFFSET 0x560
#define SYNCPT_INT_THRESH_24_RESET  0x00000000
typedef union syncpt_int_thresh_24_u {
    struct {
        unsigned int int_thresh_24:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_24_t;

#define SYNCPT_INT_THRESH_25_OFFSET 0x564
#define SYNCPT_INT_THRESH_25_RESET  0x00000000
typedef union syncpt_int_thresh_25_u {
    struct {
        unsigned int int_thresh_25:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_25_t;

#define SYNCPT_INT_THRESH_26_OFFSET 0x568
#define SYNCPT_INT_THRESH_26_RESET  0x00000000
typedef union syncpt_int_thresh_26_u {
    struct {
        unsigned int int_thresh_26:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_26_t;

#define SYNCPT_INT_THRESH_27_OFFSET 0x56C
#define SYNCPT_INT_THRESH_27_RESET  0x00000000
typedef union syncpt_int_thresh_27_u {
    struct {
        unsigned int int_thresh_27:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_27_t;

#define SYNCPT_INT_THRESH_28_OFFSET 0x570
#define SYNCPT_INT_THRESH_28_RESET  0x00000000
typedef union syncpt_int_thresh_28_u {
    struct {
        unsigned int int_thresh_28:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_28_t;

#define SYNCPT_INT_THRESH_29_OFFSET 0x574
#define SYNCPT_INT_THRESH_29_RESET  0x00000000
typedef union syncpt_int_thresh_29_u {
    struct {
        unsigned int int_thresh_29:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_29_t;

#define SYNCPT_INT_THRESH_30_OFFSET 0x578
#define SYNCPT_INT_THRESH_30_RESET  0x00000000
typedef union syncpt_int_thresh_30_u {
    struct {
        unsigned int int_thresh_30:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_30_t;

#define SYNCPT_INT_THRESH_31_OFFSET 0x57C
#define SYNCPT_INT_THRESH_31_RESET  0x00000000
typedef union syncpt_int_thresh_31_u {
    struct {
        unsigned int int_thresh_31:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_int_thresh_31_t;

#define SYNCPT_BASE_OFFSET 0x600
#define SYNCPT_BASE_RESET  0x00000000
typedef union syncpt_base_u {
    struct {
        unsigned int base_0:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_base_t;

#define SYNCPT_BASE_1_OFFSET 0x604
#define SYNCPT_BASE_1_RESET  0x00000000
typedef union syncpt_base_1_u {
    struct {
        unsigned int base_1:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_base_1_t;

#define SYNCPT_BASE_2_OFFSET 0x608
#define SYNCPT_BASE_2_RESET  0x00000000
typedef union syncpt_base_2_u {
    struct {
        unsigned int base_2:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_base_2_t;

#define SYNCPT_BASE_3_OFFSET 0x60C
#define SYNCPT_BASE_3_RESET  0x00000000
typedef union syncpt_base_3_u {
    struct {
        unsigned int base_3:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_base_3_t;

#define SYNCPT_BASE_4_OFFSET 0x610
#define SYNCPT_BASE_4_RESET  0x00000000
typedef union syncpt_base_4_u {
    struct {
        unsigned int base_4:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_base_4_t;

#define SYNCPT_BASE_5_OFFSET 0x614
#define SYNCPT_BASE_5_RESET  0x00000000
typedef union syncpt_base_5_u {
    struct {
        unsigned int base_5:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_base_5_t;

#define SYNCPT_BASE_6_OFFSET 0x618
#define SYNCPT_BASE_6_RESET  0x00000000
typedef union syncpt_base_6_u {
    struct {
        unsigned int base_6:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_base_6_t;

#define SYNCPT_BASE_7_OFFSET 0x61C
#define SYNCPT_BASE_7_RESET  0x00000000
typedef union syncpt_base_7_u {
    struct {
        unsigned int base_7:16;
        unsigned int undefined_bits_16_31:16;
    };

    uint32_t reg32;
} syncpt_base_7_t;

#define SYNCPT_CPU_INCR_OFFSET 0x700
#define SYNCPT_CPU_INCR_RESET  0x00000000
typedef union syncpt_cpu_incr_u {
    struct {
        unsigned int syncpt_cpu_incr_vector:32;
    };

    uint32_t reg32;
} syncpt_cpu_incr_t;

#define CBREAD0_OFFSET 0x720
#define CBREAD0_RESET  0x00000000
typedef union cbread_u {
    struct {
        unsigned int cbread:32;            /* Channel 0 command FIFO read */
    };

    uint32_t reg32;
} cbread_t;

#define CBREAD1_OFFSET 0x724
#define CBREAD1_RESET  0x00000000
typedef union cbread1_u {
    struct {
        unsigned int cbread1:32;            /* Channel 1 command FIFO read */
    };

    uint32_t reg32;
} cbread1_t;

#define CBREAD2_OFFSET 0x728
#define CBREAD2_RESET  0x00000000
typedef union cbread2_u {
    struct {
        unsigned int cbread2:32;            /* Channel 2 command FIFO read */
    };

    uint32_t reg32;
} cbread2_t;

#define CBREAD3_OFFSET 0x72C
#define CBREAD3_RESET  0x00000000
typedef union cbread3_u {
    struct {
        unsigned int cbread3:32;            /* Channel 3 command FIFO read */
    };

    uint32_t reg32;
} cbread3_t;

#define CBREAD4_OFFSET 0x730
#define CBREAD4_RESET  0x00000000
typedef union cbread4_u {
    struct {
        unsigned int cbread4:32;            /* Channel 4 command FIFO read */
    };

    uint32_t reg32;
} cbread4_t;

#define CBREAD5_OFFSET 0x734
#define CBREAD5_RESET  0x00000000
typedef union cbread5_u {
    struct {
        unsigned int cbread5:32;            /* Channel 5 command FIFO read */
    };

    uint32_t reg32;
} cbread5_t;

#define CBREAD6_OFFSET 0x738
#define CBREAD6_RESET  0x00000000
typedef union cbread6_u {
    struct {
        unsigned int cbread6:32;            /* Channel 6 command FIFO read */
    };

    uint32_t reg32;
} cbread6_t;

#define CBREAD7_OFFSET 0x73C
#define CBREAD7_RESET  0x00000000
typedef union cbread7_u {
    struct {
        unsigned int cbread7:32;            /* Channel 7 command FIFO read */
    };

    uint32_t reg32;
} cbread7_t;

#define REGF_DATA_OFFSET 0x740
#define REGF_DATA_RESET  0x00000000
typedef union regf_data_u {
    struct {
        unsigned int regf_data:32;          /* Register FIFO data read */
    };

    uint32_t reg32;
} regf_data_t;

#define REGF_ADDR_OFFSET 0x744
#define REGF_ADDR_RESET  0x00000000
typedef union regf_addr_u {
    struct {
        unsigned int regf_offset:16;        /* Register FIFO offset read */
        unsigned int regf_be:4;             /* Register FIFO byte enables */
        unsigned int regf_moduleid:8;       /* Register FIFO module ID read 0 = HOST1X 1 = MPE 2 = VI 3 = EPP 4 = ISP 5 = GR2D 6 = GR3D 8 = DISPLAY 11 = TVO 9 = DISPLAYB 12 = DSI 10 = HDMI */
        unsigned int regf_rwn:1;            /* Register FIFO read/write signal read 0 = WRITE 1 = READ */
        unsigned int undefined_bits_29_31:3;
    };

    uint32_t reg32;
} regf_addr_t;

#define WAITOVR_OFFSET 0x748
#define WAITOVR_RESET  0x00000000
typedef union waitovr_u {
    struct {
        unsigned int waitovr0:1;            /* Channel 0 WAIT override 0 = DISABLE 1 = ENABLE */
        unsigned int waitovr1:1;            /* Channel 1 WAIT override 0 = DISABLE 1 = ENABLE */
        unsigned int waitovr2:1;            /* Channel 2 WAIT override 0 = DISABLE 1 = ENABLE */
        unsigned int waitovr3:1;            /* Channel 3 WAIT override 0 = DISABLE 1 = ENABLE */
        unsigned int waitovr4:1;            /* Channel 4 WAIT override 0 = DISABLE 1 = ENABLE */
        unsigned int waitovr5:1;            /* Channel 5 WAIT override 0 = DISABLE 1 = ENABLE */
        unsigned int waitovr6:1;            /* Channel 6 WAIT override 0 = DISABLE 1 = ENABLE */
        unsigned int waitovr7:1;            /* Channel 7 WAIT override 0 = DISABLE 1 = ENABLE */
        unsigned int undefined_bits_8_31:24;
    };

    uint32_t reg32;
} waitovr_t;

#define CFPEEK_CTRL_OFFSET 0x74C
#define CFPEEK_CTRL_RESET  0x00000000
typedef union cfpeek_ctrl_u {
    struct {
        unsigned int cfpeek_addr:9;
        unsigned int undefined_bits_9_15:7;
        unsigned int cfpeek_channr:3;
        unsigned int undefined_bits_19_30:12;
        unsigned int cfpeek_ena:1;
    };

    uint32_t reg32;
} cfpeek_ctrl_t;

#define CFPEEK_READ_OFFSET 0x750
#define CFPEEK_READ_RESET  0x00000000
typedef union cfpeek_read_u {
    struct {
        unsigned int cfpeek_data:32;
    };

    uint32_t reg32;
} cfpeek_read_t;

#define CFPEEK_PTRS_OFFSET 0x754
#define CFPEEK_PTRS_RESET  0x00000000
typedef union cfpeek_ptrs_u {
    struct {
        unsigned int cf_rd_ptr:9;
        unsigned int undefined_bits_9_15:7;
        unsigned int cf_wr_ptr:9;
        unsigned int undefined_bits_25_31:7;
    };

    uint32_t reg32;
} cfpeek_ptrs_t;

#define CBSTAT0_OFFSET 0x758
#define CBSTAT0_RESET  0x00000000
typedef union cbstat_u {
    struct {
        unsigned int cboffset:16;          /* Channel 0 command processor current offset */
        unsigned int cbclass:10;           /* Channel 0 command processor current class */
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} cbstat_t;

#define CBSTAT1_OFFSET 0x75C
#define CBSTAT1_RESET  0x00000000
typedef union cbstat1_u {
    struct {
        unsigned int cboffset1:16;          /* Channel 1 command processor current offset */
        unsigned int cbclass1:10;           /* Channel 1 command processor current class */
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} cbstat1_t;

#define CBSTAT2_OFFSET 0x760
#define CBSTAT2_RESET  0x00000000
typedef union cbstat2_u {
    struct {
        unsigned int cboffset2:16;          /* Channel 2 command processor current offset */
        unsigned int cbclass2:10;           /* Channel 2 command processor current class */
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} cbstat2_t;

#define CBSTAT3_OFFSET 0x764
#define CBSTAT3_RESET  0x00000000
typedef union cbstat3_u {
    struct {
        unsigned int cboffset3:16;          /* Channel 3 command processor current offset */
        unsigned int cbclass3:10;           /* Channel 3 command processor current class */
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} cbstat3_t;

#define CBSTAT4_OFFSET 0x768
#define CBSTAT4_RESET  0x00000000
typedef union cbstat4_u {
    struct {
        unsigned int cboffset4:16;          /* Channel 4 command processor current offset */
        unsigned int cbclass4:10;           /* Channel 4 command processor current class */
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} cbstat4_t;

#define CBSTAT5_OFFSET 0x76C
#define CBSTAT5_RESET  0x00000000
typedef union cbstat5_u {
    struct {
        unsigned int cboffset5:16;          /* Channel 5 command processor current offset */
        unsigned int cbclass5:10;           /* Channel 5 command processor current class */
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} cbstat5_t;

#define CBSTAT6_OFFSET 0x770
#define CBSTAT6_RESET  0x00000000
typedef union cbstat6_u {
    struct {
        unsigned int cboffset6:16;          /* Channel 6 command processor current offset */
        unsigned int cbclass6:10;           /* Channel 6 command processor current class */
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} cbstat6_t;

#define CBSTAT7_OFFSET 0x774
#define CBSTAT7_RESET  0x00000000
typedef union cbstat7_u {
    struct {
        unsigned int cboffset7:16;          /* Channel 7 command processor current offset */
        unsigned int cbclass7:10;           /* Channel 7 command processor current class */
        unsigned int undefined_bits_26_31:6;
    };

    uint32_t reg32;
} cbstat7_t;

#define CDMA_STATS_WORDS_FETCHED_OFFSET 0x898
#define CDMA_STATS_WORDS_FETCHED_RESET  0x00000000
typedef union cdma_stats_words_fetched_u {
    struct {
        unsigned int cdma_words_fetched:32;
    };

    uint32_t reg32;
} cdma_stats_words_fetched_t;

#define CDMA_STATS_WORDS_DISCARDED_OFFSET 0x89C
#define CDMA_STATS_WORDS_DISCARDED_RESET  0x00000000
typedef union cdma_stats_words_discarded_u {
    struct {
        unsigned int cdma_words_discarded:32;
    };

    uint32_t reg32;
} cdma_stats_words_discarded_t;

#define CFG_OFFSET 0x94C
#define CFG_RESET  0x00FF0000
typedef union cfg_u {
    struct {
        unsigned int disable_use_idle_div:1;/* Prevent use of low freq clock */
        unsigned int undefined_bits_1_15:15;
        unsigned int idle_wait_cnt:16;      /* Number of idle cycles to wait before changing divider */
    };

    uint32_t reg32;
} cfg_t;

#define RDMA_MISC_OFFSET 0x8A0
#define RDMA_MISC_RESET  0x00001000
typedef union rdma_misc_u {
    struct {
        unsigned int rdma_rect_allow_last:1;
        unsigned int rdma_clken_ovr:1;
        unsigned int rdma_force_jpege_stride:1;
        unsigned int rdma_clken_simple:1;
        unsigned int rdma_reset_pend_mem_req:1;
        unsigned int undefined_bits_5_7:3;
        unsigned int rdma_rect_align:1;
        unsigned int undefined_bits_9_11:3;
        unsigned int rdma_hndsk_stall:1;
        unsigned int undefined_bits_13_31:19;
    };

    uint32_t reg32;
} rdma_misc_t;

#define RDMA_ARB_COUNT_OFFSET 0x8C0
#define RDMA_ARB_COUNT_RESET  0x00000000
typedef union rdma_arb_count_u {
    struct {
        unsigned int rdma_arb_count:4;
        unsigned int undefined_bits_4_31:28;
    };

    uint32_t reg32;
} rdma_arb_count_t;

#define RDMA_CONFIG_OFFSET 0x8C4
#define RDMA_CONFIG_RESET  0x00000000
typedef union rdma_config_u {
    struct {
        unsigned int rdma_rectangular_buffer:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} rdma_config_t;

#define RDMA_WRAP_OFFSET 0x8C8
#define RDMA_WRAP_RESET  0x00000000
typedef union rdma_wrap_u {
    struct {
        unsigned int rdma_wrap:1;
        unsigned int undefined_bits_1_31:31;
    };

    uint32_t reg32;
} rdma_wrap_t;

#define RDMA_STATUS0_OFFSET 0x8CC
#define RDMA_STATUS0_RESET  0x00000000
#define RDMA_STATUS0_WRMASK 0xFFF00000
typedef union rdma_status0_u {
    struct {
        unsigned int rdma_wrapped0:1;       /* read DMA port wrapped to base address */
        unsigned int rdma_outfentries0:6;   /* number of 32-bit words in read DMA fifo. Note: hardcoded to ensure SW backward compatibility if buffer is scaled down later. */
        unsigned int rdma_pendbufrdy0:9;    /* number of pending buffer_rdy's (pending buffers in memory) */
        unsigned int rdma_pend_mem_req0:4;  /* pending memory requests on port0 */
        unsigned int undefined_bits_20_31:12;
    };

    uint32_t reg32;
} rdma_status0_t;

#define RDMA_BUFFER_THRESHOLD0_OFFSET 0x8D0
#define RDMA_BUFFER_THRESHOLD0_RESET  0x00000000
typedef union rdma_buffer_threshold0_u {
    struct {
        unsigned int buffer_threshold0:9;   /* Threshold of number of buffers pending in memory at which an interrupt is generated */
        unsigned int databuf_threshold0:6;  /* Threshold of number of words in out_fifo at which an interrupt is generated */
        unsigned int undefined_bits_15_31:17;
    };

    uint32_t reg32;
} rdma_buffer_threshold0_t;

#define RDMA_CONF0_OFFSET 0x8D4
#define RDMA_CONF0_RESET  0x00000000
typedef union rdma_conf0_u {
    struct {
        unsigned int rdma_num_buffers0:9;   /* Number of buffers defined for read DMA FIFO0 */
        unsigned int rdma_num_lines0:12;    /* Rectangular reads: Number of lines per buffer */
        unsigned int rdma_store_hdr0:1;     /* Store header with bufferdata in DMA fifo (data is sent to DSP/CPU) */
        unsigned int undefined_bits_22_31:10;
    };

    uint32_t reg32;
} rdma_conf0_t;

#define RDMA_SWAP0_OFFSET 0x8D8
#define RDMA_SWAP0_RESET  0x00000000
typedef union rdma_swap0_u {
    struct {
        unsigned int rdma_data_swap0:2;
        unsigned int rdma_header_swap0:2;
        unsigned int undefined_bits_4_31:28;
    };

    uint32_t reg32;
} rdma_swap0_t;

#define RDMA_LINE0_OFFSET 0x8DC
#define RDMA_LINE0_RESET  0x00000000
typedef union rdma_line0_u {
    struct {
        unsigned int rdma_line_stride0:12;  /* rectangular reads: line_stride(bytes); JPEGE: buffer_stride (16 byte aligned!!) */
        unsigned int rdma_line_width0:12;   /* rectangular reads: line_width (bytes) */
        unsigned int rdma_line_msb_stride0:4;
        unsigned int rdma_line_msb_width0:4;
    };

    uint32_t reg32;
} rdma_line0_t;

#define RDMA_CLID0_OFFSET 0x8E0
#define RDMA_CLID0_RESET  0x00000000
typedef union rdma_clid0_u {
    struct {
        unsigned int rdma_clientid0:4;
        unsigned int undefined_bits_4_31:28;
    };

    uint32_t reg32;
} rdma_clid0_t;

#define RDMA_BADDR0_OFFSET 0x8E4
#define RDMA_BADDR0_RESET  0x00000000
typedef union rdma_baddr0_u {
    struct {
        unsigned int rdma_base_addr_lsb0:2;
        unsigned int rdma_base_addr0:30;
    };

    uint32_t reg32;
} rdma_baddr0_t;

#define RDMA_DMATRIGGER0_OFFSET 0x8E8
#define RDMA_DMATRIGGER0_RESET  0x00000000
typedef union rdma_dmatrigger0_u {
    struct {
        unsigned int rdma_buf_init0:1;      /* buffer_init: initializes read DMA port */
        unsigned int rdma_buf_rdy0:1;       /* buffer_rdy : indicates buffer is pending in memory */
        unsigned int rdma_last_buf0:1;      /* last_buffer: indicates this is the last buffer in a chain */
        unsigned int undefined_bits_3_31:29;
    };

    uint32_t reg32;
} rdma_dmatrigger0_t;

#endif // TEGRA_HOST1X_SYNCPTS_H
